version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: localizer_mongo
    volumes:
      - ./mongo-volumes:/data/db
  backend:
    build: ./
    container_name: localizer_backend
    env_file:
      - .env
    environment:
      - MONGO=mongodb://mongodb:27017/localizer
    ports:
      - "1337:1337"
    depends_on:
      - mongodb
